### ISSUE TITLE
VERA Monitor overlay crash

### ISSUE THREAD

**Issue by ZeroByteOrg** [indigodarkwolf/box16#24] opened 2021-07-26 15:49 UTC
Setting H scale value to 0 crashes the emulator. This is easy to do inadvertently by backspacing the current value out of the input field when you intend to erase it and change it to something new.

**Comment by ZeroByteOrg** [comment] 2021-07-26 15:53
Setting the actual register to zero in-emu (e.g. POKE $9F2A,0) does not crash the emulator.

**Comment by indigodarkwolf** [comment] 2021-08-02 23:03
I haven't been able to reproduce this. Has it since been fixed?

**Comment by ZeroByteOrg** [comment] 2021-08-10 02:39
Apparently it's fixed. I don't get a crash if I set H to zero anymore.

**Comment by indigodarkwolf** [comment] 2021-08-10 02:45
Awesomesauce. Closing, can always re-open if it comes back.

**Closed by indigodarkwolf** 2021-08-10 02:45 UTC
